name: Commons
version: ${fullVersion}
description: Gerenciamento de contas, permissoes e comandos
authors: [GustavoInacio]
main: br.com.battlebits.commons.bukkit.BukkitMain
load: STARTUP
depend: [ProtocolLib]
api-version: "1.12"